fstream_task/fstream_task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('root.urls'))
]

fstream_task/root/urls.py
from django.urls import path, include
from . import views


app_name = 'root'

urlpatterns = [
    path('', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('register/', views.UserRegistrationView.as_view(), name='user_registration'),
    path('message/', views.MsgToAdminView.as_view(), name='user_email_to_admin'),
]

fstream_task/root/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings


class MsgToAdmin(models.Model):
    STATUS = (
        (0, 'Unsent'),
        (1, 'Sent')
    )

    sender = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='messages')
    email = models.EmailField(choices=settings.ADMINS, verbose_name='To admin email')
    text = models.TextField(max_length=600)
    status = models.SmallIntegerField(choices=STATUS, default=STATUS[0][0])
    date_creation = models.DateTimeField('Creation date', auto_now_add=True)

    class Meta:
        verbose_name = 'Message to admin'
        verbose_name_plural = 'Messages to admins'
        ordering = ('id',)

    def __str__(self):
        return 'Message details'

fstream_task/root/forms.py
from django_registration.forms import RegistrationFormUniqueEmail

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from django.forms import widgets
from django import forms
from django.conf import settings


from .models import MsgToAdmin


class UserRegistrationForm(RegistrationFormUniqueEmail):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2', 'email']:

            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs = {'class': 'form-control'}


class UserAuthenticationForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs = {'class': 'form-control'}


class MsgToAdminForm(ModelForm):

    class Meta:
        model = MsgToAdmin
        fields = ('email', 'text')
        widgets = {
            'text': widgets.Textarea(attrs={'class': 'form-control', 'minlength': '20'}),
            'email': widgets.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'email': 'Choose admin email',
            'text': 'Write the message',
        }

fstream_task/root/views.py
import smtplib

from django.core.mail import send_mail
from django.contrib.auth.views import FormView, LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login

from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserRegistrationForm, UserAuthenticationForm, MsgToAdminForm
from .models import MsgToAdmin


class UserRegistrationView(CreateView):

    form_class = UserRegistrationForm
    template_name = 'root/registration.html'
    success_url = reverse_lazy('root:user_email_to_admin')

    def form_valid(self, form):
        
        to_the_endpoint = super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        registered_user = authenticate(username=username, password=password)
        login(self.request, registered_user)
        
        return to_the_endpoint

    def form_invalid(self, form):

        response = {
            'errors': form.errors
        }
    
        return JsonResponse(response)


class UserLoginView(LoginView):

    form_class = UserAuthenticationForm
    template_name = 'root/login.html'
    extra_context = {
        'next': reverse_lazy('root:user_email_to_admin')
    }

    def form_valid(self, form):
        super().form_valid(form)

        response = {
            'success_login_redirect': form.data['next']
        }

        return JsonResponse(response)

    def form_invalid(self, form):

        response = {
            'errors': form.errors
        }

        return JsonResponse(response)


class UserLogoutView(LogoutView):
    next_page = '/'


class MsgToAdminView(LoginRequiredMixin, FormView):

    form_class = MsgToAdminForm
    template_name = 'root/message.html'
    success_url = reverse_lazy('root:user_email_to_admin')
    login_url = reverse_lazy('root:user_login')

    def form_valid(self, form):

        message = form.cleaned_data['text']
        sender = self.request.user
        sender_email = sender.email
        recipient = form.cleaned_data['email']

        try:
            result = 0
            result = send_mail(
                subject='Subject heading',
                message=message,
                from_email=sender_email,
                recipient_list=[recipient]
            )
        except smtplib.SMTPException as e:

            print('*'*15)
            print('the error is... ' + str(e))
            print('*'*15)

        finally:
            unsent = 0
            sent = 1

            status = sent if result == 1 else unsent

            c = MsgToAdmin(
                sender=sender,
                email=recipient,
                text=message,
                status=MsgToAdmin.STATUS[status][0]
            )
            c.save()

        response = {
            'msg': 'Message was successfully sent'
        }

        return JsonResponse(response)

    def form_invalid(self, form):

        response = {
            'errors': form.errors
        }

        return JsonResponse(response)

fstream_task/fstream_task/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block include_css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/sitewide.css' %}">

    <title>{% block title %}django{% endblock %}</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    {% block include_js %}{% endblock %}
</head>

<body>
{% if user.is_authenticated %}
    <div class="container bg-light">
        <div class="col text-center">
             Hello, {{ user.username }}
        </div>
    </div>
{% endif %}

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
</html>

fstream_task/root/templates/root/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Authorization {% endblock %}


{% block content %}
<div class="w360 block-align">
    {% if user.is_authenticated %}
    <h1 class="heading1 text-center">Logout</h1>

    <div class="text-center">You can write a <a href="{% url 'root:user_email_to_admin' %}">message</a> to admin</div>

    <form method='post' action="{% url 'root:user_logout' %}">{% csrf_token %}
        <div class="horiz-align-center">
            <button type="submit" class="btn btn-primary"> Exit </button>
        </div>
    </form>
    {% else %}
    <h1 class="heading1 text-center">Login</h1>

    <div class="text-center">You can a <a href="{% url 'root:user_registration' %}">register</a> new user</div>

    <form action="{% url 'root:user_login' %}" method="post" id="login_form">{% csrf_token %}
        <div class="err" id="login_err"></div>
        {{form.as_p}}
        <div class="horiz-align-center">
            <button type="submit" class="btn btn-primary"> Login </button>
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% else %}
            <input type="hidden" name="next" value="{{ next }}" />
            {% endif %}
        </div>
    </form>
    <script>
        $(document).ready(function(){

            $('#login_form').on('submit', function(e) {
                e.preventDefault();

                t = $(this);
                subbtn = t.find('button[type="submit"]');

                subbtn.prop({'disabled': true});

                $.ajax({

                    url: t.attr('action'),
                    type: 'POST',
                    data: t.serialize(),
                    dataType: 'json',

                    success: function(serverdata) {
                        
                        if(serverdata['errors']) {
                            errs = serverdata['errors'];
                            err_block = t.find('#login_err');
                            err_block.empty();
                            ul = $('<ul></ul>');

                            for(let i in errs){
            
                                li = $('<li></li>');

                                if(i == '__all__') {
                                    li.text(errs[i]);
                                }
                                else{
                                    li.text(i + ': ' + errs[i]);
                                }
                                
                                ul.append(li);
                            }

                            err_block.append(ul);                            
                        } 
                        else {
                            let redirect_delay = 300;
                            setTimeout(function() {
                                window.location.replace(serverdata['success_login_redirect']);
                            }, redirect_delay)
                        }

                        subbtn.prop({'disabled': false});
                    },
                    error: function(xhr, status, error) {
                        subbtn.prop({'disabled': false});
                        console.log(' ' + status + ' ' + error);
                    }

               }); 
            });
        });

    </script>
    {% endif %}
</div>
{% endblock %}

fstream_task/root/templates/root/message.html
{% extends 'base.html' %}

{% block title %} Message to admin {% endblock %}

{% block include_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
{% endblock %}

{% block include_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
{% endblock %}


{% block content %}
<div class="w360 block-align">
    <h1 class="heading1 text-center">Message to admin</h1>
    
    <form action="{% url 'root:user_email_to_admin' %}" method="post" id="mail_to_admin_form">{%csrf_token%}
        <div id="err-msgs"></div>
        {{form.as_p}}
        <div class="horiz-align-center">
            <button type="submit" class="btn btn-primary" id="send_btn"> Send </button>
        </div>
    </form>

    <div class="modal" id="jqmodal-succ">
        <p></p>
    </div>

</div>

<script>
    $(document).ready(function(){

        $('#mail_to_admin_form').on('submit', function(e){
            e.preventDefault();
            
            t = $(this)
            modal_window = $('#jqmodal-succ');
            subbtn = t.find('button[type="submit"]');
            subbtn.prop({'disabled': true});

            $.ajax({
                url: t.attr('action'),
                type: 'POST',
                data: t.serialize(),
                dataType: 'json',


                success: function(serverdata){

                    if(serverdata['errors']){
                        errs = serverdata['errors'];

                        err_block = t.find('#err-msgs');
                        err_block.empty();
                        ul = $('<ul></ul>');

                        for(let i in errs){
            
                            if(i == 'email'){
                                li = $('<li></li>');
                                li.text('Admin '+ i + ': ' + errs[i]);
                                ul.append(li);
                            }

                            if(i == 'text'){
                                li = $('<li></li>');
                                li.text('Message ' + i + ': ' + errs[i]);
                                ul.append(li);
                            }
                        }

                        err_block.append(ul); 
                    }
                    else {
                        msg = serverdata['msg'];
                        modal_window.find('p').text(msg);
                        modal_window.modal();
                        modal_window.find('a[rel="modal:close"]')
                                    .css({'top': '-3px', 'right': '-3px'});
                        t[0].reset(); // reset the form
                    }

                    subbtn.prop({'disabled': false});

                },
                error: function(xhr, status, error){
                    subbtn.prop({'disabled': false});
                }

            })


        })

    });
</script>
{% endblock %}

fstream_task/root/templates/root/registration.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Registration {% endblock %}


{% block content %}
<div class="w360 block-align">
    <h1 class="heading1 text-center">Registration</h1>

    <div class="text-center">You can <a href="{% url 'root:user_login' %}">login</a>, if you have an account</div>

    <form action="{% url 'root:user_registration' %}" method="post" id="reg_form">{% csrf_token %}
        <div class="reg_err" id="reg_err"></div>
        {{ form.as_p }}
        <div class="horiz-align-center">
            <button type="submit" class="btn btn-primary">GO!</button>
        </div>
    </form>
    <script>
        $(document).ready(function(){

            $('#reg_form').on('submit', function(e) {
               e.preventDefault();

               	t = $(this);
               	subbtn = t.find('button[type="submit"]');
            	subbtn.prop({'disabled': true});

               	$.ajax({

                    url: t.attr('action'),
                    type: 'POST',
                    data: t.serialize(),
                    dataType: 'json',

                    success: function(serverdata) {
     
                        if(serverdata['errors']) {
                            errs = serverdata['errors'];
                            err_block = t.find('#reg_err');
                            err_block.empty();
                            ul = $('<ul></ul>');

                            for(let i in errs){
            					console.log(i, errs[i])
			                	li = $('<li></li>');

			                	if(errs[i].length > 1){
			                		for(j in errs[i]){
			                			li.append('<div>' + errs[i][j] + '</div>')
			                		}
			                	}
			                	else{
			                		li.text(i + ': ' + errs[i])
			                	}

			                	ul.append(li)
                			}

                            err_block.append(ul)
                        }
                        
            			subbtn.prop({'disabled': false});
                    },
                    error: function(xhr, status, error) {
            			subbtn.prop({'disabled': false});

                        console.log(' ' + status + ' ' + error);
                    }

               }); 
            });

            // function traverse_through(errs, ul) {
            // 	for(let i in errs){
            //     	if(errs[i].length > 1) {
            //     		traverse_through(errs[i], ul)
            //     	}
            //     	li = $('<li></li>');
            //     	li.text(errs[i])
            //     	ul.append(li)
            //     }
            // }
        });

    </script>
</div>
{% endblock %}